export const data = [
  {
    imageUrl:
      "https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg?auto=compress&cs=tinysrgb&w=800",
    alternate: "House",
    price: "$2096/month",
    name: "Palm harbour",
    state: "Florida",
    city: "Florida",
    headline: "63719 Keebler Rapids, Suite 693 Florida, FL, USA",
    details: {
      beds: "3 Beds",
      bathrooms: "3 Bathrooms",
      length: 5,
      width: 7,
    },
    dateAvailableFrom: "2022-11-06",
    id: 1,
    propertyType: "Mansion",
  },
  {
    imageUrl:
      "https://images.pexels.com/photos/221540/pexels-photo-221540.jpeg",
    alternate: "House",
    price: "$3659/month",
    name: "Beverley SpringField",
    state: "California",
    city: "San Francisco",
    headline:
      "3217 Weissnat Summit, Suite 025, Concord, San Francisco, CA, USA",
    details: {
      beds: "4 Beds",
      bathrooms: "5 Bathrooms",
      length: 8,
      width: 6,
    },
    dateAvailableFrom: "2022-11-15",
    id: 2,
    propertyType: "Pent House",
  },
  {
    imageUrl:
      "https://images.pexels.com/photos/259685/pexels-photo-259685.jpeg?cs=srgb&dl=pexels-pixabay-259685.jpg&fm=jpg&_gl=1*3ob7l7*_ga*MTI5NTg5NjI1Ny4xNjY4MjczMDg4*_ga_8JE65Q40S6*MTY2ODUwMTAwMC4zLjEuMTY2ODUwMTA5NC4wLjAuMA..",
    alternate: "House",
    price: "$5522/month",
    name: "Faulkner Ave",
    state: "New York",
    city: "New York",
    headline: "29490 Guillermo Freeway, Apt. 416, Queens, NY, USA",
    details: {
      beds: "4 Beds",
      bathrooms: "5 Bathrooms",
      length: 8,
      width: 6,
    },
    dateAvailableFrom: "2022-11-12",
    id: 3,
    propertyType: "Apartment",
  },
  {
    imageUrl:
      "https://images.pexels.com/photos/10430976/pexels-photo-10430976.jpeg?auto=compress&cs=tinysrgb&w=800",
    alternate: "House",
    price: "$2222/month",
    name: "Palm Villa",
    state: "Washington",
    city: "Seattle",
    headline: "401 Guido Drive, Apt. 063, Seattle, WA, USA",
    details: {
      beds: "2 Beds",
      bathrooms: "3 Bathrooms",
      length: 5,
      width: 7,
    },
    dateAvailableFrom: "2022-12-10",
    id: 4,
    propertyType: "Apartment",
  },
  {
    imageUrl:
      "https://images.pexels.com/photos/323781/pexels-photo-323781.jpeg?cs=srgb&dl=pexels-expect-best-323781.jpg&fm=jpg&_gl=1*12x6u25*_ga*MTI5NTg5NjI1Ny4xNjY4MjczMDg4*_ga_8JE65Q40S6*MTY2ODUwMTAwMC4zLjEuMTY2ODUwMTEyMi4wLjAuMA..",
    alternate: "House",
    price: "$6561/month",
    name: "The Mansion",
    state: "New York",
    city: "New York",
    headline: "696 Chelsey Freeway, Apt. 791, Queens, NY, USA",
    details: {
      beds: "4 Beds",
      bathrooms: "3 Bathrooms",
      length: 7,
      width: 7,
    },
    dateAvailableFrom: "2022-11-25",
    id: 5,
    propertyType: "Pent House",
  },
  {
    imageUrl:
      "https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?cs=srgb&dl=pexels-pixabay-208736.jpg&fm=jpg&_gl=1*dimvic*_ga*MTI5NTg5NjI1Ny4xNjY4MjczMDg4*_ga_8JE65Q40S6*MTY2ODUwMTAwMC4zLjAuMTY2ODUwMTAwNS4wLjAuMA..",
    alternate: "House",
    price: "$7122/month",
    name: "Mansion",
    state: "Miami",
    city: "Florida",
    headline: "49801 Jessica Rest, Suite 165, Florida, US",
    details: {
      beds: "4 Beds",
      bathrooms: "3 Bathrooms",
      length: 7,
      width: 7,
    },
    dateAvailableFrom: "2022-12-15",
    id: 6,
    propertyType: "Mansion",
  },

  {
    imageUrl:
      "https://images.pexels.com/photos/534228/pexels-photo-534228.jpeg?cs=srgb&dl=pexels-pixabay-534228.jpg&fm=jpg&_gl=1*1hsv366*_ga*MTI5NTg5NjI1Ny4xNjY4MjczMDg4*_ga_8JE65Q40S6*MTY2ODUwMTAwMC4zLjEuMTY2ODUwMjA0MS4wLjAuMA..",
    alternate: "House",
    price: "$3400/month",
    name: "Hansen Vista",
    state: "Nevada",
    city: "Las Vegas",
    headline: "49801 Summit, Suite 6865,Las Vegas, NV, US",
    details: {
      beds: "44Beds",
      bathrooms: "2 Bathrooms",
      length: 5,
      width: 8,
    },
    dateAvailableFrom: "2022-12-15",
    id: 7,
    propertyType: "Villa",
  },
  {
    imageUrl:
      "https://images.pexels.com/photos/1105754/pexels-photo-1105754.jpeg?cs=srgb&dl=pexels-jens-mahnke-1105754.jpg&fm=jpg&_gl=1*ztl9q6*_ga*MTI5NTg5NjI1Ny4xNjY4MjczMDg4*_ga_8JE65Q40S6*MTY2ODUwMTAwMC4zLjEuMTY2ODUwMjQxOS4wLjAuMA..",
    alternate: "House",
    price: "$8150/month",
    name: "Odessa Motorway",
    state: "Washington",
    city: "Seattle",
    headline: "5639 Walter Plains, Apt. 4065, Seattle, US",
    details: {
      beds: "5 Beds",
      bathrooms: "4 Bathrooms",
      length: 10,
      width: 8,
    },
    dateAvailableFrom: "2022-12-15",
    id: 8,
    propertyType: "Pent House",
  },
  {
    imageUrl:
      "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?cs=srgb&dl=pexels-binyamin-mellish-1396122.jpg&fm=jpg&_gl=1*1jc661h*_ga*MTI5NTg5NjI1Ny4xNjY4MjczMDg4*_ga_8JE65Q40S6*MTY2ODUwMTAwMC4zLjEuMTY2ODUwMjQ1NS4wLjAuMA..",
    alternate: "House",
    price: "$4250/month",
    name: "Witting Road",
    state: "California",
    city: "San Francisco",
    headline: "127 Lynch Extensions, Suite 601, Florida, US",
    details: {
      beds: "5 Beds",
      bathrooms: "5 Bathrooms",
      length: 9,
      width: 9,
    },
    dateAvailableFrom: "2022-11-22",
    id: 9,
    propertyType: "Villa",
  },
];
