export const data = [
  {
    imageUrl: "https://images.alphacoders.com/435/435117.jpg",
    alternate: "House",
    price: "$2096/month",
    name: "Palm harbour",
    state: "Florida",
    city: "Florida",
    headline: "299, Green ValleyHighland Lake Florida, FL, USA",
    details: {
      beds: "3 Beds",
      bathrooms: "3 Bathrooms",
      length: 5,
      width: 7,
    },
    dateAvailableFrom: "2022-11-06",
    id: 1,
    propertyType: "Mansion",
  },
  {
    imageUrl:
      "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?cs=srgb&dl=pexels-binyamin-mellish-106399.jpg&fm=jpg&_gl=1*1bd5wq*_ga*MTI5NTg5NjI1Ny4xNjY4MjczMDg4*_ga_8JE65Q40S6*MTY2ODI3MzA4OS4xLjEuMTY2ODI3MzA5NS4wLjAuMA..",
    alternate: "House",
    price: "$3659/month",
    name: "Beverley SpringField",
    state: "California",
    city: "San Francisco",
    headline: "456, Walnut Creek, Concord, San Francisco, CA, USA",
    details: {
      beds: "4 Beds",
      bathrooms: "5 Bathrooms",
      length: 8,
      width: 6,
    },
    dateAvailableFrom: "2022-11-15",
    id: 2,
    propertyType: "Pent House",
  },
  {
    imageUrl:
      "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?cs=srgb&dl=pexels-binyamin-mellish-1396122.jpg&fm=jpg&_gl=1*1hgfja*_ga*MTI5NTg5NjI1Ny4xNjY4MjczMDg4*_ga_8JE65Q40S6*MTY2ODI3MzA4OS4xLjEuMTY2ODI3MzMwMi4wLjAuMA..",
    alternate: "House",
    price: "$5522/month",
    name: "Faulkner Ave",
    state: "New York",
    city: "New York",
    headline: "678, Green Valley Highland, Queens, NY, USA",
    details: {
      beds: "4 Beds",
      bathrooms: "5 Bathrooms",
      length: 8,
      width: 6,
    },
    dateAvailableFrom: "2022-11-12",
    id: 3,
    propertyType: "Apartment",
  },
  {
    imageUrl:
      "https://images.pexels.com/photos/164558/pexels-photo-164558.jpeg?cs=srgb&dl=pexels-pixabay-164558.jpg&fm=jpg&_gl=1*k9gwqm*_ga*MTI5NTg5NjI1Ny4xNjY4MjczMDg4*_ga_8JE65Q40S6*MTY2ODI3MzA4OS4xLjEuMTY2ODI3NTQ0MC4wLjAuMA..",
    alternate: "House",
    price: "$2222/month",
    name: "Palm Villa",
    state: "Washington",
    city: "Seattle",
    headline: "890, Green Valley Highland, Seattle, WA, USA",
    details: {
      beds: "2 Beds",
      bathrooms: "3 Bathrooms",
      length: 5,
      width: 7,
    },
    dateAvailableFrom: "2022-12-10",
    id: 4,
    propertyType: "house",
  },
  {
    imageUrl:
      "https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?cs=srgb&dl=pexels-pixabay-280222.jpg&fm=jpg&_gl=1*13gxdqv*_ga*MTI5NTg5NjI1Ny4xNjY4MjczMDg4*_ga_8JE65Q40S6*MTY2ODI3MzA4OS4xLjEuMTY2ODI3NDY4OC4wLjAuMA..",
    alternate: "House",
    price: "$6561/month",
    name: "The Mansion",
    state: "New York",
    city: "New York",
    headline: "98106 Rodriguez Port, Apt. 268, Queens, NY, USA",
    details: {
      beds: "4 Beds",
      bathrooms: "3 Bathrooms",
      length: 7,
      width: 7,
    },
    dateAvailableFrom: "2022-11-25",
    id: 5,
    propertyType: "Pent House",
  },
  {
    imageUrl:
      "https://images.pexels.com/photos/32870/pexels-photo.jpg?cs=srgb&dl=pexels-chris-goodwin-32870.jpg&fm=jpg&_gl=1*1vdmcav*_ga*MTI5NTg5NjI1Ny4xNjY4MjczMDg4*_ga_8JE65Q40S6*MTY2ODI3MzA4OS4xLjEuMTY2ODI3NDg0My4wLjAuMA..",
    alternate: "House",
    price: "$7122/month",
    name: "Mansion",
    state: "California",
    city: "Los Angeles",
    headline: "7027 Bergnaum Light, Apt. 270, LA, United States",
    details: {
      beds: "4 Beds",
      bathrooms: "3 Bathrooms",
      length: 7,
      width: 7,
    },
    dateAvailableFrom: "2022-12-15",
    id: 6,
    propertyType: "Mansion",
  },
];
